// This script was generated by OpenAI's ChatGPT, and brought to you by Jake Bartlett's mostly incompetent script editing abilities. Use at your own risk. www.jakeinmotion.com
// This script will select matching properties to the current selection in selected layers of the active comp.

// Create an undo group
app.beginUndoGroup("Shy Locked Layers");

// Get the active composition
var activeComp = app.project.activeItem;

// Check if the active item is a composition
if (activeComp && activeComp instanceof CompItem) {

  // Loop through all the layers in the composition
  for (var i = 1; i <= activeComp.numLayers; i++) {

    // Get the layer
    var layer = activeComp.layer(i);

    // Check if the layer is shied
    if (layer.shy) {

      // Enable the lock switch
      layer.locked = true;
    }
  }
}

// End the undo group
app.endUndoGroup();